version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: cavecontrol-db
    environment:
      POSTGRES_USER: uaua
      POSTGRES_PASSWORD: uaua
      POSTGRES_DB: cavecontrol_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cavecontrol-network

volumes:
  postgres_data:

networks:
  cavecontrol-network:
    driver: bridge
